name: Pro Profile Automation

on:
  schedule:
    - cron: "15 9 * * *"    # 09:15 UTC
    - cron: "50 7 * * *"   # 13:30 UTC
    - cron: "45 16 * * *"   # 16:45 UTC
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Important! prevents GH token override

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run automation and push using PAT
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          python3 generate.py

          cd aws-devops
          git add .
          git commit -m "Day $(( $(date +%j) )): automated learning update" || echo "Nothing to commit"
          git push https://$REPO_TOKEN@github.com/sbp828/aws-devops.git HEAD:main
